// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetLinkRequest struct {
	ShortLink            string   `protobuf:"bytes,1,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	ShortLinkKey         string   `protobuf:"bytes,2,opt,name=short_link_key,json=shortLinkKey,proto3" json:"short_link_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinkRequest) Reset()         { *m = GetLinkRequest{} }
func (m *GetLinkRequest) String() string { return proto.CompactTextString(m) }
func (*GetLinkRequest) ProtoMessage()    {}
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *GetLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinkRequest.Unmarshal(m, b)
}
func (m *GetLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinkRequest.Marshal(b, m, deterministic)
}
func (m *GetLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinkRequest.Merge(m, src)
}
func (m *GetLinkRequest) XXX_Size() int {
	return xxx_messageInfo_GetLinkRequest.Size(m)
}
func (m *GetLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinkRequest proto.InternalMessageInfo

func (m *GetLinkRequest) GetShortLink() string {
	if m != nil {
		return m.ShortLink
	}
	return ""
}

func (m *GetLinkRequest) GetShortLinkKey() string {
	if m != nil {
		return m.ShortLinkKey
	}
	return ""
}

type GetLinkResponse struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinkResponse) Reset()         { *m = GetLinkResponse{} }
func (m *GetLinkResponse) String() string { return proto.CompactTextString(m) }
func (*GetLinkResponse) ProtoMessage()    {}
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *GetLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinkResponse.Unmarshal(m, b)
}
func (m *GetLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinkResponse.Marshal(b, m, deterministic)
}
func (m *GetLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinkResponse.Merge(m, src)
}
func (m *GetLinkResponse) XXX_Size() int {
	return xxx_messageInfo_GetLinkResponse.Size(m)
}
func (m *GetLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinkResponse proto.InternalMessageInfo

func (m *GetLinkResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type AddShortLinkRequest struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShortLinkRequest) Reset()         { *m = AddShortLinkRequest{} }
func (m *AddShortLinkRequest) String() string { return proto.CompactTextString(m) }
func (*AddShortLinkRequest) ProtoMessage()    {}
func (*AddShortLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *AddShortLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShortLinkRequest.Unmarshal(m, b)
}
func (m *AddShortLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShortLinkRequest.Marshal(b, m, deterministic)
}
func (m *AddShortLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShortLinkRequest.Merge(m, src)
}
func (m *AddShortLinkRequest) XXX_Size() int {
	return xxx_messageInfo_AddShortLinkRequest.Size(m)
}
func (m *AddShortLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShortLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddShortLinkRequest proto.InternalMessageInfo

func (m *AddShortLinkRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type AddShortLinkResponse struct {
	ShortLink            string   `protobuf:"bytes,1,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	ShortLinkKey         string   `protobuf:"bytes,2,opt,name=short_link_key,json=shortLinkKey,proto3" json:"short_link_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShortLinkResponse) Reset()         { *m = AddShortLinkResponse{} }
func (m *AddShortLinkResponse) String() string { return proto.CompactTextString(m) }
func (*AddShortLinkResponse) ProtoMessage()    {}
func (*AddShortLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *AddShortLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShortLinkResponse.Unmarshal(m, b)
}
func (m *AddShortLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShortLinkResponse.Marshal(b, m, deterministic)
}
func (m *AddShortLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShortLinkResponse.Merge(m, src)
}
func (m *AddShortLinkResponse) XXX_Size() int {
	return xxx_messageInfo_AddShortLinkResponse.Size(m)
}
func (m *AddShortLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShortLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddShortLinkResponse proto.InternalMessageInfo

func (m *AddShortLinkResponse) GetShortLink() string {
	if m != nil {
		return m.ShortLink
	}
	return ""
}

func (m *AddShortLinkResponse) GetShortLinkKey() string {
	if m != nil {
		return m.ShortLinkKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLinkRequest)(nil), "model.GetLinkRequest")
	proto.RegisterType((*GetLinkResponse)(nil), "model.GetLinkResponse")
	proto.RegisterType((*AddShortLinkRequest)(nil), "model.AddShortLinkRequest")
	proto.RegisterType((*AddShortLinkResponse)(nil), "model.AddShortLinkResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x51, 0x0a, 0xe5, 0xe2, 0x73, 0x4f, 0x2d, 0xf1, 0xc9, 0xcc, 0xcb, 0x0e, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe5, 0xe2, 0x2a, 0xce, 0xc8, 0x2f, 0x2a, 0x89, 0xcf, 0xc9, 0xcc,
	0xcb, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x04, 0x8b, 0x80, 0x54, 0x09, 0xa9, 0x70,
	0xf1, 0x21, 0xa4, 0xe3, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0xc0, 0x4a, 0x78, 0xe0, 0x4a, 0xbc, 0x53,
	0x2b, 0x95, 0x54, 0xb9, 0xf8, 0xe1, 0xc6, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09, 0x71,
	0xb1, 0x20, 0x99, 0x08, 0x66, 0x2b, 0x69, 0x72, 0x09, 0x3b, 0xa6, 0xa4, 0x04, 0xc3, 0x74, 0xc2,
	0x9c, 0x80, 0x4d, 0x69, 0x34, 0x97, 0x08, 0xaa, 0x52, 0xa8, 0xb1, 0xd4, 0x70, 0xae, 0xd1, 0x64,
	0x46, 0x2e, 0xae, 0xa0, 0x82, 0xe4, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x2b, 0x2e,
	0x76, 0xa8, 0xeb, 0x85, 0x44, 0xf5, 0xc0, 0xe1, 0xa4, 0x87, 0x1a, 0x48, 0x52, 0x62, 0xe8, 0xc2,
	0x10, 0xd7, 0x28, 0x31, 0x08, 0x79, 0x72, 0xf1, 0x20, 0xbb, 0x53, 0x48, 0x0a, 0xaa, 0x12, 0x8b,
	0x3f, 0xa5, 0xa4, 0xb1, 0xca, 0xc1, 0x8c, 0x4a, 0x62, 0x03, 0xc7, 0x94, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x79, 0x9b, 0xd3, 0x4c, 0xbb, 0x01, 0x00, 0x00,
}
